name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 and Run Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.23.159.186 << 'EOF'
            docker pull stenny1710/job-app-backend:latest
            docker stop job-app || true
            docker rm job-app || true
            docker run -d -p 8000:8000 --name job-app stenny1710/job-app-backend:latest
          EOF
